### ISSUE TITLE
No clear way to exit the sample program

### ISSUE THREAD

**Issue by amirzia** [mehdy/pyeez#1]
I ran the sample code (awesome.py) and it worked as it supposed to. But it was not clear to me how I can exit the program.
I propose to assign a key like `q` (as in **top** and **htop**) for exiting the programs.

**Comment by mehdy** [comment]
Yeah, you're right. I don't think of it as an bug though since the `Ctrl+c` does the job. But I'm completely onboard to improve the exit key bindings.

I suggest we should have an exit function and we could assign different key strokes to it.
It's good the assign `Esc`, `q` and `Ctrl+c` by default but we have to let the user override it.

You may start working on it 😊
